version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/server/Startup"
    schedule:
      interval: "weekly"
    labels:
      - "nuget"
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    labels:
      - "npm"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "github_actions"
      - "dependencies"