services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${APPOPTIONS__POSTGRES__USERNAME:-user}
      - POSTGRES_PASSWORD=${APPOPTIONS__POSTGRES__PASSWORD:-pass}
      - POSTGRES_DB=${APPOPTIONS__POSTGRES__DATABASE:-db}
    ports:
      - '${APPOPTIONS__POSTGRES__PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  
  flyway:
    image: flyway/flyway:latest
    depends_on:
      - postgres
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/${APPOPTIONS__POSTGRES__DATABASE:-db}
      FLYWAY_USER: ${APPOPTIONS__POSTGRES__USERNAME:-user}
      FLYWAY_PASSWORD: ${APPOPTIONS__POSTGRES__PASSWORD:-pass}
      FLYWAY_CONNECT_RETRIES: 5
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
    volumes:
      - ./db/migrations:/flyway/sql
    command: migrate
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    restart: always
    
  seq:
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - '5341:80'
    volumes:
      - seq_data:/data
    restart: unless-stopped
    
  vernemq:
    image: vernemq/vernemq
    ports:
      - "${APPOPTIONS__MQTT__MQTTPORT:-1883}:1883"      # Standard MQTT port for ESP32
      - "${APPOPTIONS__MQTT__WEBSOCKETPORT:-8080}:8080" # MQTT over WebSockets for browser klienter, f.eks. HiveMQTT .NET client
    environment:
      - DOCKER_VERNEMQ_ACCEPT_EULA=yes        # Accepterer 'End User License Agreement' (EULA) ligesom for Seq
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=off    # Gør sådan at man skal autentificere sig
      - DOCKER_VERNEMQ_USER_${APPOPTIONS__MQTT__USERNAME:-user}=${APPOPTIONS__MQTT__PASSWORD:-pass}
    volumes:
      - vernemq-data:/var/lib/vernemq # Behøves ikke, men gør sådan at vi kan opbevare data
    restart: unless-stopped # Gør sådan at broker genstarter på system reboot

volumes:
  postgres_data:
  vernemq-data:
  seq_data: