services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${APPOPTIONS__POSTGRES__USERNAME:-user}
      - POSTGRES_PASSWORD=${APPOPTIONS__POSTGRES__PASSWORD:-pass}
      - POSTGRES_DB=${APPOPTIONS__POSTGRES__DATABASE:-db}
    ports:
      - '${APPOPTIONS__POSTGRES__PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  
  flyway:
    image: flyway/flyway:latest
    depends_on:
      - postgres
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/${APPOPTIONS__POSTGRES__DATABASE:-db}
      FLYWAY_USER: ${APPOPTIONS__POSTGRES__USERNAME:-user}
      FLYWAY_PASSWORD: ${APPOPTIONS__POSTGRES__PASSWORD:-pass}
      FLYWAY_CONNECT_RETRIES: 5
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
    volumes:
      - ./db/migrations:/flyway/sql
    command: migrate
    
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1
    ports:
      - '${APPOPTIONS__DRAGONFLY__PORT:-6379}:6379'
    volumes:
      - dragonflydata:/data
  
  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    restart: always

volumes:
  postgres_data:
  dragonflydata:
