name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET tools
        run: |
          dotnet tool install -g dotnet-sonarscanner
          dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Initialize SonarQube analysis
        # Kan ikke køre SonarQube ordentlig på flere branches hvis man har Community Edition og Developer koster 500$ om året
        if: (github.ref == 'refs/heads/master' || github.event_name == 'pull_request')
        env:
          SONARQUBE_PROJECT_KEY: ${{ vars.SONARQUBE_PROJECT_KEY }}
          SONARQUBE_SERVER: ${{ vars.SONARQUBE_SERVER }}
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number || '' }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          chmod +x .github/scripts/sonarqube_config.py
          python .github/scripts/sonarqube_config.py

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
        
      - name: Run .NET tests
        run: |
          chmod +x .github/scripts/run_dotnet_tests.py
          python .github/scripts/run_dotnet_tests.py

      - name: Generate test summary
        if: always()
        run: |
          chmod +x .github/scripts/generate_test_summary.py
          python .github/scripts/generate_test_summary.py

      - name: Generate code coverage report
        if: always()
        run: |
          chmod +x .github/scripts/generate_coverage_report.py
          python .github/scripts/generate_coverage_report.py

      - name: Complete SonarQube analysis
        if: always() && (github.ref == 'refs/heads/master' || github.event_name == 'pull_request')
        run: |
          dotnet sonarscanner end \
          /d:sonar.token="${{ secrets.SONARQUBE_TOKEN }}"

      - name: Install Python dependencies # Skal bruges i 'Generate SonarQube Summary' for at hente data fra SonarQube server
        if: always() && (github.ref == 'refs/heads/master' || github.event_name == 'pull_request')
        run: pip install requests

      - name: Generate SonarQube Summary
        if: always() && (github.ref == 'refs/heads/master' || github.event_name == 'pull_request')
        env:
          SONARQUBE_SERVER: ${{ vars.SONARQUBE_SERVER }}
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONARQUBE_PROJECT_KEY: ${{ vars.SONARQUBE_PROJECT_KEY }}
        run: |
          chmod +x .github/scripts/generate_sonarqube_summary.py
          python .github/scripts/generate_sonarqube_summary.py

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: '**/TestResults/*.html'
          retention-days: 7

      - name: Upload code coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-report
          retention-days: 7

  mutation-tests:
    strategy:
      matrix:
        project: [
          'server/Infrastructure.Data/Infrastructure.Data.csproj',
          'server/Application/Application.csproj',
          'server/Core/Core.csproj'
        ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET tools
        run: |
          dotnet tool install -g dotnet-stryker 

      - name: Build
        run: dotnet build

      - name: Run Stryker mutation tests
        # Har ikke threshold med her for at kunne få summary
        # Men se sidste trin i dette som tjekker for om vi rammer 80%
        run: |
          SAFE_NAME=$(echo "${{ matrix.project }}" | tr '/' '_')
          dotnet stryker --project "${{ matrix.project }}" --output "StrykerOutput_${SAFE_NAME}" --reporter "json" --reporter "html" | tee "stryker-output-${SAFE_NAME}.log"

      - name: Upload Stryker JSON report for ${{ matrix.project }}
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mutation-json-report-${{ strategy.job-index }}
          path: StrykerOutput_*/reports/mutation-report.json 
          retention-days: 1 # Skal kun bruges til næste job

      - name: Upload Stryker HTML report for ${{ matrix.project }}
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: stryker-html-report-${{ strategy.job-index }}
          path: StrykerOutput_*/reports/mutation-report.html
          retention-days: 7
          
  aggregate-mutation-results:
    runs-on: ubuntu-latest
    needs: mutation-tests
    if: always() # For at få overordnet summary tabel selvom en fejler
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all JSON reports
        uses: actions/download-artifact@v4
        with:
          pattern: mutation-json-report-* 
          path: all-mutation-reports

      - name: List downloaded files 
        run: ls -R all-mutation-reports

      - name: Aggregate reports and generate final summary
        id: aggregate 
        run: |
          chmod +x .github/scripts/aggregate_mutation_summary.py
          python .github/scripts/aggregate_mutation_summary.py ./all-mutation-reports

      - name: Check final mutation threshold (80%)
        env:
          FINAL_MUTATION_SCORE: ${{ env.MUTATION_SCORE }}
        run: |
          echo "Final Overall Mutation Score: $FINAL_MUTATION_SCORE%"
          if [[ -z "$FINAL_MUTATION_SCORE" ]]; then
            echo "::error::Could not determine final mutation score."
            exit 1
          fi
          if [[ $FINAL_MUTATION_SCORE -lt 80 ]]; then
            echo "::error::Overall Mutation score ($FINAL_MUTATION_SCORE%) is below threshold (80%)"
            exit 1
          else
            echo "Overall Mutation score meets threshold requirement"
          fi