name: CI/CD Pipeline

on:
  push:
    paths:
      - 'server/**'
      - 'client/**'
      - 'PlaywrightTests/**'
      - 'Directory.Build.props'
      - '.github/**'
    branches:
      - '**'

jobs:
  e2e-tests:
    name: Run E2E tests
    runs-on: ubuntu-latest
    if: success() && (github.ref == 'refs/heads/master')
    timeout-minutes: 20
    strategy:
      matrix:
        browser: [ chromium, firefox, webkit ]
      fail-fast: false
    env:
      E2E_TEST_DIR: PlaywrightTests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true
          cache-dependency-path: ${{ env.E2E_TEST_DIR }}/packages.lock.json

      - name: Restore dependencies
        run: |
          cd ${{ env.E2E_TEST_DIR }}
          dotnet restore

      - name: Build project
        run: |
          cd ${{ env.E2E_TEST_DIR }}
          dotnet build --no-restore

      - name: Install Playwright browsers
        run: |
          cd ${{ env.E2E_TEST_DIR }}
          pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps ${{ matrix.browser }}

      - name: Run Playwright tests
        run: |
          cd ${{ env.E2E_TEST_DIR }}
          mkdir -p TestResults
          dotnet test \
            --logger "trx;LogFileName=TestResults-${{ matrix.browser }}.trx" \
            --logger "html;LogFileName=TestResults-${{ matrix.browser }}.html" \
            --results-directory "./TestResults"
        env:
          PLAYWRIGHT_TEST_BASE_URL: http://${{ vars.STAGING_DOMAIN_NAME }}

      - name: Generate test summary
        if: always()
        run: |
          cd ${{ env.E2E_TEST_DIR }}
          chmod +x ../../.github/scripts/generate_test_summary.py
          python ../../.github/scripts/generate_test_summary.py

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.browser }}-${{ github.sha }}
          path: ${{ env.E2E_TEST_DIR }}/TestResults
          retention-days: 30